In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
movies = pd.read_json('data/IMDB_movie_details.json', lines = True)

In [2]:
movies.head()

,movie_id,plot_summary,duration,genre,rating,release_date,plot_synopsis
0,tt0105112,"Former CIA analyst, Jack Ryan is in England wi...",1h 57min,"[Action, Thriller]",6.9,1992-06-05,"Jack Ryan (Ford) is on a ""working vacation"" in..."
1,tt1204975,"Billy (Michael Douglas), Paddy (Robert De Niro...",1h 45min,[Comedy],6.6,2013-11-01,Four boys around the age of 10 are friends in ...
2,tt0243655,"The setting is Camp Firewood, the year 1981. I...",1h 37min,"[Comedy, Romance]",6.7,2002-04-11,
3,tt0040897,"Fred C. Dobbs and Bob Curtin, both down on the...",2h 6min,"[Adventure, Drama, Western]",8.3,1948-01-24,Fred Dobbs (Humphrey Bogart) and Bob Curtin (T...
4,tt0126886,Tracy Flick is running unopposed for this year...,1h 43min,"[Comedy, Drama, Romance]",7.3,1999-05-07,Jim McAllister (Matthew Broderick) is a much-a...

In [3]:
from bs4 import BeautifulSoup
import requests
import random

user_agents_list = [
    'Mozilla/5.0 (iPad; CPU OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0',
    'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.46',
    'Mozilla/5.0 (Linux; Android 10; SM-G981B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.58 Mobile Safari/537.36']

# add a bar to show the progress of the scraping
count = 0

#scrape the movie title
def get_title(movie_id):
    response = requests.get(f"https://www.imdb.com/title/{movie_id}/", headers = {'User-Agent': random.choice(user_agents_list), "Accept-Language": "en-US,en;q=0.5"})
    soup =  BeautifulSoup(response.content, 'html.parser')
    global count 
    count += 1
    if count % 100 == 0:
        print(count)
    try:
        title = soup.find('h1').text
        return title
    except:
        return None

movies['title'] = movies['movie_id'].apply(get_title)

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500

In [4]:
movies[movies.title.isna()]

,movie_id,plot_summary,duration,genre,rating,release_date,plot_synopsis,title
1570,tt0104014/,"For a while now, beautiful 24-year-old Diana B...",1h 33min,"[Comedy, Drama]",5.3,1992-02-21,,None
1571,tt0114142/,"The marriage of David Burgess, a senior execut...",1h 32min,"[Drama, Thriller]",4.0,1999-01-29,,None

In [5]:
#remove / from these two movie_ids
movies.loc[movies.title.isna() , 'movie_id'] = movies.loc[movies.title.isna() , 'movie_id'].str.replace('/','')

#scrape the movie title
def get_title(movie_id):
    response = requests.get(f"https://www.imdb.com/title/{movie_id}/", headers = {'User-Agent': random.choice(user_agents_list), "Accept-Language": "en-US,en;q=0.5"})
    soup =  BeautifulSoup(response.content, 'html.parser')
    global count 
    count += 1
    if count % 100 == 0:
        print(count)
    try:
        title = soup.find('h1').text
        return title
    except:
        return None

movies.loc[movies.title.isna(), 'title'] = movies.loc[movies.title.isna(), 'movie_id'].apply(get_title)

In [6]:
movies.to_json('data/IMDB_movie_details_eng.json')